(rule
 (targets melange_bigarray.ml melange_bigarray.mli)
 (deps
  melange_bigarray.ml.in
  ../api/4.14.4.mli
  ../api/5.2.1.mli
  ../api/5.3.0.mli
  ../tools/select_api.py)
 (action
  (run %{bin:python3} ../tools/select_api.py %{ocaml_version})))

(library
 (name melange_bigarray)
 (public_name melange-bigarray)
 (modes melange)
 (preprocess
  (pps melange.ppx)))
